### ISSUE TITLE
Installation fail

### ISSUE THREAD

**Issue by MamonthPenis** [hwipl/listnd#1]
Trying to install listnd:

user@ubuntu:~/Desktop$ go get github.com/hwipl/listnd/cmd/listnd
 github.com/hwipl/listnd/internal/pkt
../go/src/github.com/hwipl/listnd/internal/pkt/dhcp.go:44:8: undefined: layers.DHCPv6MsgTypeAdverstise

**Comment by hwipl** [comment]
Thanks for the report.

Seems like there is a typo in the gopacket library version, that listnd uses. This typo is fixed in the latest gopacket code. Not sure, why your go tool pulled a newer version than what listnd requires.

I updated listnd to use the latest gopacket code. That should fix this issue. Could you test it?

**Comment by MamonthPenis** [comment]
Tried again go get github.com/hwipl/listnd/cmd/listnd.  
Same error

**Comment by hwipl** [comment]
Have you tried `go get -u github.com/hwipl/listnd/cmd/listnd`?

**Comment by MamonthPenis** [comment]
Now it works. Thanks!
